### PR TITLE
Fix  #726: Status bar wrong theme in dark mode

### LINKED ISSUE #726: FluffyChat starting in dark mode have wrong theming for system buttons and status bar
### Bug Description

When starting FluffyChat with dark mode, status bar and system buttons are having a wrong theming.

### Steps to Reproduce

Set FluffyChat theme settings on dark mode
Kill FluffyChat
Restart it

### Expected Behavior

Theming should be correct

### App Version

1.16.0

### Additional Platform Information

Xperia XZ, Android Oreo (8.0), ROM stock

### Additional Context

See the screenshots below for comparison: interestingly, when toggling dark mode, the theming is correct after the switch. It's on next application start that theming is wrong.

<details>
<summary>
Screenshots
</summary>

Application just started and settings were set on dark mode previously:
Screenshot_20231217-015225

Settings were just switched to dark mode without application restart:
Screenshot_20231217-015348

</details>

My issue can be a dupe of https://github.com/krille-chan/fluffychat/issues/32 and/or https://github.com/krille-chan/fluffychat/issues/59 but screenshots are dead there so in doubt I opened this one. Feel free to close for dupe if it's the same.
Also note that this Android version didn't have dark/light mode yet (so system theme can't work).

### PR DESCRIPTION
**Pull request by itz-shubham**
As stated by the issuer, this may be a duplicate of issue #32 and/or #59. If so, then close both those issues also.

### CODE REVIEW

**Review by krille-chan — APPROVED** [review]
Thank you very much. LGTM 👍

**Comment by itz-shubham** [comment]
Fingers crossed, I hope this time it will successfully merge

**Comment by krille-chan** [comment]
> @krille-chan Maybe you need to give a positive review as a review was requested? I don't know if that's the reason, but auto-merge seems to be stuck again…

Hello, the reason is that the commits are not signed. Can you maybe sign them and force push to this branch?

**Comment by itz-shubham** [comment]
> @itz-shubham for the signing requirement (I'm not the author of those commits).

I'm new to the pull request process, so I checked the "Allow edits by maintainers" box. This should allow you to tweak the code or add comments as needed before merging. Meanwhile, I'm learning about GPG and how to sign commits.

**Comment by krille-chan** [comment]
> > @itz-shubham for the signing requirement (I'm not the author of those commits).
> 
> I'm new to the pull request process, so I checked the "Allow edits by maintainers" box. This should allow you to tweak the code or add comments as needed before merging. Meanwhile, I'm learning about GPG and how to sign commits.

Can you please squash your commits to a single one which then has a valid signature? Then we can merge it. If I edit your Pull Request, then I would be the new author in the git history which would be incorrect

**Comment by itz-shubham** [comment]
I am trying to solve signing from yesterday. and I think I did accidentally  👀

**Comment by itz-shubham** [comment]
Whenever I trying to squash all my commits in one I am getting dependency error before that every thing working fine without any dependency error

Here is the log

```
[fluffychat] flutter pub get --no-example
"be": 633 untranslated message(s).
"bn": 629 untranslated message(s).
"bo": 633 untranslated message(s).
"ca": 36 untranslated message(s).
"cs": 118 untranslated message(s).
"de": 1 untranslated message(s).
"el": 583 untranslated message(s).
"eo": 284 untranslated message(s).
"es": 139 untranslated message(s).
"eu": 2 untranslated message(s).
"fa": 141 untranslated message(s).
"fi": 104 untranslated message(s).
"fil": 458 untranslated message(s).
"fr": 140 untranslated message(s).
"ga": 269 untranslated message(s).
"he": 388 untranslated message(s).
"hi": 626 untranslated message(s).
"hu": 1 untranslated message(s).
"ia": 619 untranslated message(s).
"id": 7 untranslated message(s).
"ie": 392 untranslated message(s).
"it": 58 untranslated message(s).
"ja": 170 untranslated message(s).
"ka": 486 untranslated message(s).
"lt": 170 untranslated message(s).
"lv": 7 untranslated message(s).
"nb": 334 untranslated message(s).
"nl": 97 untranslated message(s).
"pl": 88 untranslated message(s).
"pt": 611 untranslated message(s).
"pt_BR": 1 untranslated message(s).
"pt_PT": 335 untranslated message(s).
"ro": 142 untranslated message(s).
"sk": 401 untranslated message(s).
"sl": 529 untranslated message(s).
"sr": 305 untranslated message(s).
"sv": 38 untranslated message(s).
"ta": 630 untranslated message(s).
"th": 583 untranslated message(s).
"uk": 38 untranslated message(s).
"vi": 484 untranslated message(s).
"zh_Hant": 282 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Resolving dependencies...
Downloading packages...
  _fe_analyzer_shared 67.0.0 (72.0.0 available)
  analyzer 6.4.1 (6.7.0 available)
  archive 3.4.10 (3.6.1 available)
  barbecue 0.4.0 (0.5.0 available)
  collection 1.18.0 (1.19.0 available)
  coverage 1.7.2 (1.8.0 available)
  csslib 0.17.3 (1.0.0 available)
  dart_webrtc 1.4.4 (1.4.6+hotfix.1 available)
  dependency_validator 3.2.3 (4.1.0 available)
  file_picker 8.0.2 (8.0.5 available)
  file_selector_macos 0.9.3+3 (0.9.4 available)
  flutter_foreground_task 6.2.0 (6.5.0 available)
  flutter_layout_grid 2.0.6 (2.0.7 available)
  flutter_lints 3.0.2 (4.0.0 available)
  flutter_local_notifications 17.1.0 (17.1.2 available)
  flutter_map 6.1.0 (7.0.1 available)
  flutter_olm 1.3.2 (1.4.1 available)
  flutter_openssl_crypto 0.3.0 (0.5.0 available)
  flutter_plugin_android_lifecycle 2.0.19 (2.0.20 available)
  flutter_ringtone_player 4.0.0+2 (4.0.0+3 available)
  flutter_secure_storage 9.0.0 (9.2.2 available)
! flutter_secure_storage_linux 1.1.3 (overridden) (1.2.1 available)
  flutter_secure_storage_macos 3.0.1 (3.1.2 available)
  flutter_secure_storage_platform_interface 1.0.2 (1.1.2 available)
  flutter_secure_storage_web 1.1.2 (1.2.1 available)
  flutter_secure_storage_windows 3.0.0 (3.1.2 available)
  flutter_web_auth_2 3.1.1 (3.1.2 available)
  flutter_webrtc 0.10.3 (0.11.1 available)
  frontend_server_client 3.2.0 (4.0.0 available)
  geolocator 7.7.1 (12.0.0 available)
! geolocator_android 1.0.1 (overridden)
  geolocator_apple 1.2.2 (2.3.7 available)
  geolocator_platform_interface 2.3.6 (4.2.3 available)
  geolocator_web 2.0.6 (4.0.0 available)
  go_router 14.0.1 (14.2.0 available)
  gradient_borders 1.0.0 (1.0.1 available)
  http_parser 4.0.2 (4.1.0 available)
  image 4.1.7 (4.2.0 available)
  image_picker 1.1.0 (1.1.2 available)
  image_picker_android 0.8.10 (0.8.12+3 available)
  image_picker_ios 0.8.10+1 (0.8.12 available)
  js 0.6.7 (0.7.1 available)
  just_audio 0.9.37 (0.9.38 available)
  just_audio_platform_interface 4.2.2 (4.3.0 available)
  just_audio_web 0.4.9 (0.4.11 available)
! keyboard_shortcuts 0.1.4 from git https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git at a3d402 (overridden)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  lints 3.0.0 (4.0.0 available)
  logger 2.2.0 (2.3.0 available)
  macos_ui 2.0.5 (2.0.7 available)
  material_color_utilities 0.8.0 (0.12.0 available)
  meta 1.12.0 (1.15.0 available)
  package_info_plus 6.0.0 (8.0.0 available)
  package_info_plus_platform_interface 2.0.1 (3.0.0 available)
  pana 0.21.45 (0.22.6 available)
  path_provider_android 2.2.4 (2.2.6 available)
  path_provider_foundation 2.3.2 (2.4.0 available)
  permission_handler_android 12.0.5 (12.0.7 available)
  permission_handler_apple 9.4.4 (9.4.5 available)
  platform 3.1.4 (3.1.5 available)
  pointer_interceptor 0.10.1 (0.10.1+1 available)
  pointer_interceptor_ios 0.10.0+2 (0.10.1 available)
  pointycastle 3.9.0 (3.9.1 available)
  pubspec_parse 1.2.3 (1.3.0 available)
  receive_sharing_intent 1.4.5 (1.8.0 available)
  record 5.0.5 (5.1.1 available)
  record_android 1.1.0 (1.2.2 available)
  record_darwin 1.0.1 (1.1.0 available)
  record_platform_interface 1.0.2 (1.1.0 available)
  record_web 1.0.5 (1.1.1 available)
  record_windows 1.0.2 (1.0.3 available)
  rxdart 0.27.7 (0.28.0 available)
  shared_preferences_android 2.2.2 (2.2.3 available)
  shared_preferences_foundation 2.3.5 (2.4.0 available)
  shelf_web_socket 1.0.4 (2.0.0 available)
  sqflite 2.3.3 (2.3.3+1 available)
  sqlcipher_flutter_libs 0.6.1 (0.6.3 available)
  sqlite3 2.4.2 (2.4.3 available)
  string_validator 0.3.0 (1.1.0 available)
  tar 1.0.4 (2.0.0 available)
  test 1.25.2 (1.25.7 available)
  test_api 0.7.0 (0.7.2 available)
  test_core 0.6.0 (0.6.4 available)
  uni_links 0.5.1 (discontinued replaced by app_links)
  unorm_dart 0.2.0 (0.3.0 available)
  url_launcher 6.2.6 (6.3.0 available)
  url_launcher_android 6.3.1 (6.3.3 available)
  url_launcher_ios 6.2.5 (6.3.0 available)
  url_launcher_macos 3.1.0 (3.2.0 available)
  video_player 2.8.6 (2.8.7 available)
  video_player_android 2.4.14 (2.5.0 available)
  video_player_avfoundation 2.5.7 (2.6.1 available)
  video_player_web 2.3.0 (2.3.1 available)
  visibility_detector 0.3.3 (0.4.0+2 available)
  vm_service 14.2.1 (14.2.4 available)
  wakelock_plus 1.2.4 (1.2.5 available)
  web_socket_channel 2.4.5 (3.0.0 available)
  win32 5.5.0 (5.5.1 available)
Got dependencies!
1 package is discontinued.
96 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
exit code 0

--

[fluffychat] flutter pub get --no-example
"ar": 20 untranslated message(s).
"bn": 35 untranslated message(s).
"bo": 35 untranslated message(s).
"ca": 35 untranslated message(s).
"cs": 35 untranslated message(s).
"de": 4 untranslated message(s).
"el": 35 untranslated message(s).
"eo": 35 untranslated message(s).
"es": 35 untranslated message(s).
"et": 20 untranslated message(s).
"eu": 4 untranslated message(s).
"fa": 35 untranslated message(s).
"fi": 35 untranslated message(s).
"fr": 35 untranslated message(s).
"ga": 35 untranslated message(s).
"gl": 4 untranslated message(s).
"he": 35 untranslated message(s).
"hi": 35 untranslated message(s).
"hr": 22 untranslated message(s).
"hu": 35 untranslated message(s).
"id": 35 untranslated message(s).
"ie": 35 untranslated message(s).
"it": 20 untranslated message(s).
"ja": 35 untranslated message(s).
"ko": 35 untranslated message(s).
"lt": 35 untranslated message(s).
"lv": 35 untranslated message(s).
"nb": 35 untranslated message(s).
"nl": 35 untranslated message(s).
"pl": 35 untranslated message(s).
"pt": 35 untranslated message(s).
"pt_BR": 4 untranslated message(s).
"pt_PT": 35 untranslated message(s).
"ro": 35 untranslated message(s).
"ru": 8 untranslated message(s).
"sk": 35 untranslated message(s).
"sl": 35 untranslated message(s).
"sr": 35 untranslated message(s).
"sv": 35 untranslated message(s).
"ta": 35 untranslated message(s).
"th": 35 untranslated message(s).
"tr": 20 untranslated message(s).
"uk": 20 untranslated message(s).
"vi": 35 untranslated message(s).
"zh": 20 untranslated message(s).
"zh_Hant": 35 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Resolving dependencies...
Note: file is pinned to version 7.0.0 by integration_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of integration_test from sdk depends on file 7.0.0 and dart_code_metrics >=3.0.0-nullsafety.2 depends on file ^6.0.0, integration_test from sdk is incompatible with dart_code_metrics >=3.0.0-nullsafety.2.
So, because fluffychat depends on both dart_code_metrics ^5.7.5 and integration_test from sdk, version solving failed.
exit code 1

```

**Comment by Porkepix** [comment]
@krille-chan PR was closed without its content being pick-up; was the content relevant for the issue at hand and the cleaning of an unused service? (Current code modified by this PR doesn't seems to have changed for the last two years)

**Comment by krille-chan** [comment]
> @krille-chan PR was closed without its content being pick-up; was the content relevant for the issue at hand and the cleaning of an unused service? (Current code modified by this PR doesn't seems to have changed for the last two years)

Stale bot reminded me again to process this. Let's get it merged :)

**Comment by shubhamwhocodes** [comment]
Old sins… Sorry 🙂

**Comment by Porkepix** [comment]
> > @krille-chan PR was closed without its content being pick-up; was the content relevant for the issue at hand and the cleaning of an unused service? (Current code modified by this PR doesn't seems to have changed for the last two years)
> 
> Stale bot reminded me again to process this. Let's get it merged :)

Well… now there's no source branch anymore, but GitHub still shows a diff. Dunno why @shubhamwhocodes  you removed it, nor why auto-merge really have an issue with this PR…
Should this be taken onto another PR, or commit by you if this PR have such issues?

**Pull request closed without merging**
