### PR TITLE
Refactor: Reduce .of(context) calls theme

### PR DESCRIPTION
**Pull request by CodeThomnics**
*Thank you so much for your contribution to FluffyChat ❤️❤️❤️*

Please make sure that your Pull Request meet the following **acceptance criteria**:

 - [x] Code formatting and import sorting has been done with dart format lib/ test/ and dart run import_sorter:main --no-comments
- [x] The commit message uses the format of [Conventional Commits](https://www.conventionalcommits.org/)
- [x] The commit message describes what has been changed, why it has been changed and how it has been changed
- [x] Every new feature or change of the design/GUI is linked to an approved design proposal in an issue
- [x] Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every release, e.g. a volunteer who takes over maintainership

Pull Request has been tested on:
- [x] Android
- [ ] iOS
- [x] Browser (Chromium based)
- [ ] Browser (Firefox based)
- [ ] Browser (WebKit based)
- [x] Desktop Linux
- [ ] Desktop Windows
- [ ] Desktop macOS

### CODE REVIEW

**Review by krille-chan — APPROVED** [review]
Looks great ✌️ thank you so much

**Comment by krille-chan** [comment]
@CodeThomnics can you please sign your commits? Also please use the default pull request template to have the checklist of pre requirements. Then we can merge it

**Comment by CodeThomnics** [comment]
Thank you so much approving it! This is my first time committing to a big open source project so i started with something relatively small. I will look into signing my Pull Request and update you on it.

**Comment by CodeThomnics** [comment]
@krille-chan   I think i did it now. If i did it wrong, Please let me know

**Comment by krille-chan** [comment]
> @krille-chan   I think i did it now. If i did it wrong, Please let me know

Hmm looks like you have two commits now and one is signed, and the other not. Can you squash them?

**Comment by CodeThomnics** [comment]
@krille-chan I've managed to squash it

**Pull request merged**
