### PR TITLE
upgrade flutter to 3.16.0

### PR DESCRIPTION
**Pull request by selfisekai**
~~blocker: https://github.com/simpleclub-extended/flutter_math_fork/issues/85~~

### CODE REVIEW

**Comment by krille-chan** [comment]
Looks like we did the same at the same time while we fixed different issues :D you wanna cherry-pick my changes to the didWillPopScope and I close my PR?

**Comment by selfisekai** [comment]
sure

**Comment by selfisekai** [comment]
but there's still something up with the android pipeline here

**Comment by krille-chan** [comment]
> but there's still something up with the android pipeline here

Maybe using git import of https://github.com/famedly/flutter_openssl_crypto does fix it?

**Comment by krille-chan** [comment]
Oof, still no luck. Maybe upgrading Kotlin to 1.9.20 helps? No idea...

**Review by krille-chan — APPROVED** [review]
Thank you so much <3

**Pull request merged**
