### PR TITLE
fix: reaction not show because the width too big

### PR DESCRIPTION
**Pull request by Decodetalkers**
so I want to fix this problem

before
image

after

image

### CODE REVIEW

**Comment by q234rty** [comment]
I confirm this fixes custom reactions for me.
Gentle ping on this @krille-chan

**Comment by krille-chan** [comment]
Can you add steps to reproduce please?

**Comment by q234rty** [comment]
I assume it's just "send a custom reaction in any client that supports that, and observe that the reaction is not rendered in fluffychat"

**Comment by q234rty** [comment]
ping? `mxc://` reactions are still broken on 0.17.0

**Comment by Akselmo** [comment]
> Can you add steps to reproduce please?

1. Join to a chat that is bridged to discord with mautrix-discord bridge.

2. React to someones message with custom emoji on discord side.

3. Check fluffychat for the same message

**Comment by krille-chan** [comment]
Not sure if this is the correct approach. A `SingleChildScrollView` has a huge performance impact. If there are a lot of reactions visible on the screen, this might become laggy

**Comment by Akselmo** [comment]
Good to know, is there any different potential solutions? This isnt my PR but just asking in behalf of contributors (or maybe i could try fix it as well since i can reliably repro it! I am just not android dev at all.. 😅 )

**Comment by krille-chan** [comment]
In the latest commit on main I have no added a fix. For some reason the width of an mxc reaction was set to 9999? However just setting it to width and height of 20 seems to easily fix it for me. Or am I missing something here?

It now looks like this (tested with one of my own stickers):

Bildschirmfoto vom 2024-05-05 09-28-23
Bildschirmfoto vom 2024-05-05 09-28-32

**Comment by Decodetalkers** [comment]
but sometimes it will be a long letter. emm

**Comment by Decodetalkers** [comment]
Seems fixed, so now  I will close this pr, thanks very much

**Comment by Akselmo** [comment]
Seems to work for me as well on the web nightly at least, thanks!

**Pull request closed without merging**
