### PR TITLE
Change incorrect share icon to downlaod

### PR DESCRIPTION
**Pull request by everypizza1**

### CODE REVIEW

**Review by krille-chan — APPROVED** [review]
Thank you so much :)

**Comment by everypizza1** [comment]
I added a new commit, should compile now.

**Comment by everypizza1** [comment]
It looks like it didn't build again, I'll try to fix again. Sorry for the inconvenice.

**Review by krille-chan — CHANGES_REQUESTED** [review]
Can you squash your commits please?

**Comment by everypizza1** [comment]
I'm not entirely sure if I squashed them properly, but now GitHub Desktop is complaining about it.

**Comment by everypizza1** [comment]
> Can you squash your commits please?

Done!

**Comment by everypizza1** [comment]
I'll close this and remake it in one commit.

**Pull request closed without merging**
