### PR TITLE
fix: Bypass image compression in flutter_file_picker

### LINKED ISSUE #1168: Wrong orientation for images
### Bug Description

When I send a picture from my galerie, the preview and the final image are rotated by 90°, while the original image is not. When I share the same image from my galerie into fluffy, the orientation is the right one. Element also took the right orientation.

Surprinsingly, screnshots don't have that issue. 

Here is an exemple of a picture with this issue.

### Steps to Reproduce

1. Take a picture out of fluffy
2. Click on "Send image"
3. Select the picture taken
4. It will be rotated

### Expected Behavior

The picture should keep it original orientation

### App Version

1.20.0

### Additional Platform Information

Android LineageOS, android 13

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by q234rty**
We do our own image compression in the dark sdk anyway.

Might fix #1168

*Thank you so much for your contribution to FluffyChat ❤️❤️❤️*

Please make sure that your Pull Request meet the following **acceptance criteria**:

- [x] Code formatting and import sorting has been done with `dart format lib/ test/` and `dart run import_sorter:main --no-comments`
- [x] The commit message uses the format of [Conventional Commits](https://www.conventionalcommits.org)
- [x] The commit message describes what has been changed, why it has been changed and how it has been changed
- [x] Every new feature or change of the design/GUI is linked to an approved design proposal in an issue
- [x] Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every release, e.g. a volunteer who takes over maintainership

### Pull Request has been tested on:

- [ ] Android
- [ ] iOS
- [ ] Browser (Chromium based)
- [ ] Browser (Firefox based)
- [ ] Browser (WebKit based)
- [ ] Desktop Linux
- [ ] Desktop Windows
- [ ] Desktop macOS

### CODE REVIEW

**Comment by q234rty** [comment]
Hmmm this seems to disable compression from the dart sdk as well for some reason...

**Comment by q234rty** [comment]
Hmmm even with a debug build from 1.22.0 w/o any code modification, image compression in the matrix dart sdk does not seem to work. Let me test a release build...

**Comment by q234rty** [comment]
Marked as ready as I suspect it's an issue w/ my build that happens even w/o this PR applied.

**Review by krille-chan — CHANGES_REQUESTED** [review]
Thank you very much for your contribution. Before we merge this I would like to point out two things:

1. Does this indeed fix the orientation bug?
2. Is this maybe something that should be fixed in the filepicker package itself? Is there an issue for it?
3. There are several other places in the app where we pick files by using `FilePicker.platform.pickFiles` which have not been changed

**Comment by q234rty** [comment]
> Does this indeed fix the orientation bug?

Yes, at least in my builds...

> Is this maybe something that should be fixed in the filepicker package itself? Is there an issue for it?

There's https://github.com/miguelpruivo/flutter_file_picker/issues/1518 but it has been automatically closed. Just made a comment. 

> There are several other places in the app where we pick files by using `FilePicker.platform.pickFiles` which have not been changed

When sending an image in the chat we already asks the user whether the image should be compressed, so compression in `FilePicker.platform.pickFiles` should be disabled anyway. In other cases compression might or might not be desired so fixing those is a bit out of scope for this PR IMO.

**Review by krille-chan — APPROVED** [review]
LGTM thank you so much

**Pull request merged**
