### PR TITLE
chore: upgrade flutter to 3.24

### PR DESCRIPTION
**Pull request by selfisekai**
*Thank you so much for your contribution to FluffyChat ❤️❤️❤️*

Please make sure that your Pull Request meet the following **acceptance criteria**:

- [x] Code formatting and import sorting has been done with `dart format lib/ test/` and `dart run import_sorter:main --no-comments`
- [x] The commit message uses the format of [Conventional Commits](https://www.conventionalcommits.org)
- [ ] The commit message describes what has been changed, why it has been changed and how it has been changed
- [ ] Every new feature or change of the design/GUI is linked to an approved design proposal in an issue
- [ ] Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every release, e.g. a volunteer who takes over maintainership

### Pull Request has been tested on:

- [ ] Android
- [ ] iOS
- [ ] Browser (Chromium based)
- [ ] Browser (Firefox based)
- [ ] Browser (WebKit based)
- [ ] Desktop Linux
- [ ] Desktop Windows
- [ ] Desktop macOS

### CODE REVIEW

**Comment by krille-chan** [comment]
Looks like win32 package already moved away from UnmodifiableUint8ListView. Just need a version bump: https://pub.dev/packages/win32/changelog

**Comment by krille-chan** [comment]
Still is breaking Linux builds:

grafik

upstream issue: https://github.com/flutter/flutter/issues/152297

**Comment by krille-chan** [comment]
If we are lucky, this hotfix could be released soon: https://github.com/flutter/engine/pull/54518 ✌️

**Comment by selfisekai** [comment]
@krille-chan check now with flutter 3.24.1

**Comment by krille-chan** [comment]
> @krille-chan check now with flutter 3.24.1

I've tried it out. Now it renders but... colors are inverted :D

grafik

**Comment by krille-chan** [comment]
Update: Migrating to core24 fixes the problem for me :+1:

**Review by krille-chan — APPROVED** [review]

**Pull request merged**
